### ISSUE TITLE
User Defined Keyboard shortcuts

### ISSUE THREAD

**Issue by hermannw** [drexjj/sbitx#47]
It would be great help for those using external keyboards. I see that there are already a few function keys defined but general (user defined?)  keyboard shortcuts might be a big help.

73 de Hermann AJ4ZS

**Comment by MolKa51** [comment]
There are currently 3 operating as far as I know:
Ctrl-R switches to receive
Ctrl-T switches to transmission
Ctrl-Q exits the application
--Gyula HA3HZ--

**Comment by Mashintime** [comment]
Yes it would be nice.  If you have something specific in mind it would be more meaningful/easier to implement then a generic custom keyboard shortcuts.

**Comment by MolKa51** [comment]
Re: [drexjj/sbitx] User Defined Keyboard shortcuts (Issue #47)



Hello Mashintime,

I did not write this thought.

Wednesday, October 2, 2024, 10:51:01 PM, you wrote:





Yes it would be nice. If you have something specific in mind it would be more meaningful/easier to implement then a generic custom keyboard shortcuts.
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***>




-- 
Best regards,
Molnar Gyula
