### ISSUE TITLE
Add the ability to store and send callsigns that contain a  /  

### ISSUE THREAD

**Issue by ec1oud** [drexjj/sbitx#68]
I'm American, and operating under the CEPT agreement in Norway.  So my callsign for now is LA/K7IHZ.  Apparently some validation code somewhere is removing the slash when I use the /mycallsign command; therefore I can't use the built-in FT8 mode here.  I was just using the American callsign for a while, until I knew better...

I'm working on getting a Norwegian callsign, but it will take a while.  And there are many other cases where slashes are used in callsigns anyway.  European countries are small, and hams routinely travel across borders and need to use prefixes.  Then there are the numeric suffixes.

**Comment by drexjj** [comment]
This has been assigned to the dev team to resolve in the next release.

**Comment by ec1oud** [comment]
I found that if I change #mycallsign in the .ini file, the UI shows the callsign correctly.  I attempted FT8 on 20m that way, and made no contacts; so I wonder if the packets are formatted wrong, and thus everybody was ignoring them.  (Although activity showed up on pskreporter.info somehow.)  I don't yet have another rig to receive and decode my own transmissions.  But I had better luck making contacts with jtdx on a sota peak last night (and needed to take along an extra screen to have enough space for that).

**Comment by MolKa51** [comment]
Unfortunately, the / sign is not recognized and all complex call sign formats are not recognized by the sbitx ft8 decoder, so if you have an external hdmi monitor, use an external application (jtdx, wsjtx) installed on the 64-bit image. Once I realized this, I've been using it to access complex callsigns ever since.
Gyula HA3HZ

**Comment by Mashintime** [comment]
I wonder if the ft8 library we're currently using even supports `/`'s in call signs.  May be why they were blocked.

**Comment by MolKa51** [comment]
Re: [drexjj/sbitx] Add the ability to store and send callsigns that contain a  /   (Issue #68)



Hello Mashintime,

The wsjtx design team also had a headache with the use of extended callsigns. Sometime around 2018, this was a topic.
 I don't know if there is anyone out there who can help with this.

Wednesday, October 2, 2024, 10:45:24 PM, you wrote:





I wonder if the ft8 library we're currently using even supports /'s in call signs. May be why they were blocked.
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***>




-- 
Best regards,
Molnar Gyula

**Comment by drexjj** [comment]
We would have to find a different library to use since the current one has several limitations.

**Comment by drexjj** [comment]
Closing for now.
